# Site
repository: floydspace/floydspace.github.io
favicon: images/favicon.ico
darkmode: false

# Personal info
name: Victor Korzunin
title: Lead Software Engineer
address: Rotterdam, The Netherlands
website: floydspace.github.io

# Social links
github_username: floydspace
npm_username: f1oyd
instagram_username: victor_korzunin
linkedin_username: korzunin
twitter_username: F1oydRose

# Google Analytics and Tag Manager
gtag: UA-155264465-1

# About Section
# about_title: Profile
about_profile_image: images/profile.jpeg
about_content: |
  I have been an experienced/lead Node.js, JavaScript/TypeScript developer and engineer since 2016, and I have been working with AWS cloud since 2018. Before that, I worked as a financial markets trader and had been working in financial companies and a bank for 10 years. Lately, I have been working in fintech, where I have gained valuable experience creating innovative solutions for the financial sector. My background in finance has given me a deep understanding and appreciation of the industry, and I am passionate about leveraging my knowledge and expertise to drive positive change in this dynamic field.

# Skills Section
# skills_title: Skills

# Projects Section
projects_title: Most starred open-source projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# Certifications Section
# certifications_title: Certifications

# More Section
more_title: Hobbies
more_content: |
  Alongside my interests in software development some of my other interests and hobbies are:
   - 🏂 Snowboarding
   - 🗻 Mountain Hiking
   - 🚵 Cycling

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/modern-resume-theme
